site_name: AN
site_description: 'This site documents notes, guidelines, and research on various topics.'

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.link
    - navigation.sticky
    - navigation.section
    - navigation.path
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.suggest
    - search.share

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde

plugins:
  - include-markdown
  - search:
      prebuild_index: true
      
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/custom.css
  
nav:
  - Home: index.md  
  - Mindsets:
      - Videos: ms/yt_videos.md
      - Books: ms/neversplitdif.md
      - Podcasts: ms/podcasts.md
  - Technology:
      - ChatGPT: tech/chatgpt.md
      - Github: tech/github.md
  - Investment:
      - Value Investing:
          - Fundamental Analysis Framework: investment/value.md
      - Industries:
          - Quant: investment/quant.md
          - Semiconductor: investment/semi.md
      - Stocks:
          - Industrials: investment/stocks-ind.md
          - Semiconductor: investment/stocks-semi.md
      - Trading Strategies:
          - Indicators: investment/indicators.md
          - Options: investment/options.md
      - Stock Charts:
          - Consumer: investment/charts-consumer.md
          - Industrials: investment/charts-ind.md
          - HVAC: investment/charts-hvac.md            
          - Financials: investment/charts-financial.md
          - REIT: investment/charts-reit.md                       
          - Semiconductors: investment/charts-semi.md
          - Technology: investment/charts-tech.md
          - Growth: investment/charts-growth.md
  - Soccer:
      - Skills: soccer/skills.md
      - Agility: soccer/agility.md
      - Scan: soccer/scan.md

