site_name: Fieldpiece Inc.

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.link
    - navigation.sticky
    - navigation.section
    - navigation.path
    - content.code.copy
    - content.code.annotate

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
        
nav:
  - Home: index.md
  - Github Training:
      - Overview: github/overview.md
      - Markdown: github/mkdown.md
      - Search and Filter: github/search.md
  - Howtos: github/howtos.md
  - Contributing:
      - Naming Conventions: contributing/naming-conventions.md
      - Document Wrokflow: contributing/workflow.md
      - Document Structure: contributing/structure.md
      - Document Ownership: contributing/ownership.md
      - Commit Message: contributing/commit.md
      - Project Board: contributing/project.md

