site_name: AN
site_description: 'This site documents notes, guidelines, and research on various topics.'

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.link
    - navigation.sticky
    - navigation.section
    - navigation.path
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.suggest
    - search.share

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde

plugins:
  - search:
      prebuild_index: true
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/tradingview_widget.js


extra_css:
  - stylesheets/custom.css
  
nav:
  - Home: index.md  
  - Mindsets:
      - Videos: ms/yt_videos.md
      - Books: ms/neversplitdif.md
      - Podcasts: ms/podcasts.md
  - Technology:
      - ChatGPT: tech/chatgpt.md
      - Github: tech/github.md
  - Investment:
      - Value Investing: investment/value.md
      - Option Strategies: investment/options.md
      - Charts:
          - Industrials: investment/charts-ind.md                      
          - Semiconductors: investment/charts-semi.md
          - Technology: investment/charts-tech.md
          - REIT: investment/charts-reit.md            
      - Industries:
          - Quant: investment/quant.md
          - Semiconductor:
              - Overview: investment/semi.md
              - Equipment: investment/semi-equipment.md
              - Processor: investment/semi-processor.md
  - Soccer:
      - Body Feint: soccer/body-fient.md
      - Scan: soccer/scan.md
